### ISSUE TITLE
Exclude runtimes folder from publish

### ISSUE THREAD

**Issue by natanaelfiorilla** [HakanL/WkHtmlToPdf-DotNet#101]
Hi,
Is it possible to exclude the runtimes folder on publish?

dotnet publish "" --output "/bin/Release/net6.0/publish" --configuration "Release" --framework "net6.0" /p:GenerateRuntimeConfigurationFiles=true --runtime linux-x64 --self-contained False 

Publishing for a lambda includes /runtimes/win-x64 and  /runtimes/win-x86.
 Unfortunately, any attempt to exclude the folder using csproj file does not work. Maybe I'm not doing it correctly.
 Thanks!

**Comment by HakanL** [comment]
Good question, I don't know if there is a way to filter the runtime files based on target.

**Comment by RomanHubyak** [comment]
https://github.com/HakanL/WkHtmlToPdf-DotNet/pull/60 - The fix for .NET Framework affects .NET Core and it results in x3 binaries: 2 in /runtimes for x86 and x64, and 1 in root for the target runtime.

![image](https://github.com/HakanL/WkHtmlToPdf-DotNet/assets/46841287/4363fc05-a8d4-4d7b-9e45-978164674096)
