### ISSUE TITLE
In Linux CentOS 7, there was an error: Unable to load native library. The platform may be missing native dependencies (libjpeg62, etc). Or the current platform is not supported.

### ISSUE THREAD

**Issue by EwenGao** [HakanL/WkHtmlToPdf-DotNet#113]

**Comment by HakanL** [comment]
Most likely a library dependency is missing, see the other issues here for suggestions.

**Comment by StockDave** [comment]
i have the same issue, did u find something about it?

![image](https://github.com/HakanL/WkHtmlToPdf-DotNet/assets/10101078/d9ba3b88-25ce-4ec1-b4d3-3dc49c3393a2)

**Comment by HakanL** [comment]
The issue is exactly what the error message indicate, you're missing some native dependencies (could be libjpeg62, or any other). Since this project is just a .NET wrapper for the native library, when we try to load the native library (wkhtmltopdf), if it's missing any of its dependencies then we're just getting an error back (in .NET world) saying basically "failed to load".
