### ISSUE TITLE
License Change

### ISSUE THREAD

**Issue by PoisnFang** [HakanL/WkHtmlToPdf-DotNet#20]
I am not sure you are really allowed to Change the License of this code considering it was forked. You do not have copyright permissions to the substantial of the code base. It should stay as MIT

**Comment by PoisnFang** [comment]
Ah never mind, I see what you did:

> Fork
This library is forked from DinkToPdf. The main changes are to include the required native binaries in the package so they don't have to be manually installed, and renamed to a move appropriate project name. The license has also been corrected to match the license for the wkhtmltopdf parent project.

Because you include the binaries you have to match the wkhtmltopdf license.

**Comment by HakanL** [comment]
Yeah, I'm not sure the legality of changing the license (what MIT allows you to do), but since I include the binaries I thought it was more appropriate to mirror the license of the "main" project, vs the wrapper. But I'm no legal expert, if someone needs to audit this prior to them using this project then they should and all details are listed here.

**Comment by PoisnFang** [comment]
@HakanL  I think technically you just need to have 2 Licenses, one for the binaries and one for the C# codebase

**Comment by PoisnFang** [comment]
thats what I would do at least

**Comment by HakanL** [comment]
That may be right, but I don't know how to do that, I don't even think NuGet supports that. I'll leave it for someone else to audit.
