### ISSUE TITLE
Pdf getting shrinked after conversion from HTML.

### ISSUE THREAD

**Issue by satyarupkoley** [HakanL/WkHtmlToPdf-DotNet#49]
I am facing this weird issue , where the HTML file after conversion to PDF is getting shrinked . As a result i am getting a PDF which is shrinked to the top left corner.
Any pointers on how I can resolve the issue is appreciated.

**Comment by HakanL** [comment]
Since this is just a .NET wrapper around somebody else's native library I suggest you test it with the native library (command line) directly to understand where the problem is.

**Comment by PedroFreidinger** [comment]
I'm almost 2 years late but for those having problems with this issue, this shrinking is due to a feature in WebKit called smart shrinking (or something like that). This can be avoided by setting `EnableIntelligentShrinking = false` in a `WebSettings` obj when setting up the `HtmlToPdfDocument`. The equivalent command line argument is `--disable-smart-shrinking`.

**Comment by pedroter7** [comment]
I'm almost 2 years late but for those struggling with this issue this shrinking is due to a feature in WebKit called smart shrinking (or something like that). You can avoid it by setting `EnableIntelligentShrinking = false` in your `WebSettings` object inside the `HtmlToPdfDocument`. The equivalent command line argument to wkhtmltopdf is `--disable-smart-shrinking`.
